### ISSUE TITLE
Ini

### ISSUE THREAD

**Issue by PiMaV** [PiMaV/BLITZ#55]
Default Ini is not written anymore?

``` Python
Traceback (most recent call last):
  File "C:\PYTHON\BLITZ\blitz\layout\main.py", line 713, in sync_settings
    settings.set("data/max_ram", self.ui.spinbox_max_ram.value())
  File "C:\PYTHON\BLITZ\blitz\settings.py", line 118, in set
    SETTINGS[setting] = value
    ~~~~~~~~^^^^^^^^^
  File "C:\PYTHON\BLITZ\blitz\settings.py", line 94, in __setitem__
    type_ = type(_default_settings[setting])
                 ~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'data/max_ram'
```

When "saved" per Project manually, it saves XXX.ini.ini (ending twice)

-> default settings are crucial to be save everytime they are changed. This is true for all settings on the file tab (incl. the WOLKE connection information)

**Comment by PiMaV** [comment]
I would like to call that file XXX.blitz instead of XXX.ini
Its way easier to identify

**Comment by PiMaV** [comment]
Fixed
