### ISSUE TITLE
Out of nowhere bug

### ISSUE THREAD

**Issue by PiMaV** [PiMaV/BLITZ#63]
Traceback (most recent call last):
  File "blitz_main.py", line 8, in <module>
  File "blitz\app.py", line 22, in run
  File "blitz\layout\main.py", line 47, in __init__
  File "blitz\layout\main.py", line 354, in reset_options
  File "blitz\settings.py", line 126, in get
  File "blitz\settings.py", line 101, in __getitem__
TypeError: unable to convert a QVariant of type 10 to a QMetaType of type 2

When dragging LUT line

**Comment by irkri** [comment]
I see that this could happen. Right now, we save all settings directly in the project file. A LUT is a dictionary, which is transformed to a QVariant by the standard QSettings class. Maybe some changes lead to the LUT being not a dictionary, but something else.

We could do a quick fix like this:
Save the LUT as a `.json` file with the same name as the project `.blitz` file and remember the path of this `.json` file in the `.project`  file. It was like this in early versions of blitz, but I thought it would be better to simplify it... didn't work.

**Comment by PiMaV** [comment]
Maybe back to the roots: min and max value, as well as the colormap. Done. Rest for later

**Comment by PiMaV** [comment]
onohter one; same

Traceback (most recent call last):
  File "blitz_main.py", line 8, in <module>
  File "blitz\app.py", line 22, in run
  File "blitz\layout\main.py", line 47, in __init__
  File "blitz\layout\main.py", line 359, in reset_options
  File "blitz\settings.py", line 126, in get
  File "blitz\settings.py", line 101, in __getitem__
TypeError: unable to convert a QVariant of type 10 to a QMetaType of type 2

**Comment by PiMaV** [comment]
cant reproduce. Closed until it surfaces again
